### ISSUE TITLE
Not working correctly when window is scrolled

### ISSUE THREAD

**Issue by bacinsky** [redoPop/loupe#13]
To fix that change loupe position from fixed to absolute.
https://github.com/redoPop/loupe/blob/master/loupe.css#L17

**Comment by eliz82** [comment]
Yeah, i confirm this bug in Firefox 50

**Comment by redoPop** [comment]
Thanks for the report, and sorry for the delay in applying this fix. I've updated the example CSS to use `position: absolute` for version 2.0.1.
