### ISSUE TITLE
Destroy method doesn't work in v2.0.0

### ISSUE THREAD

**Issue by Voles** [redoPop/loupe#15]
The `destroy()` method doesn't work in v2.0.0. I've created a commit with the fix, but I'm unable to create a PR (not sure why, probably permissions).

Commit: https://github.com/redoPop/loupe/commit/1597d0311bf35087f706f5fb48d6a32c325b29a1

I see this issue is fixed on the `master` branch, but there's no release of that yet. So new users will download v2.0.0 with a broken `destroy()` method.

**Comment by redoPop** [comment]
Sorry about the delay in responding to this: I'd misconfigured my GitHub notifications and missed a few issues in my repos. D'oh!

I just cut a 2.0.1 release, which should solve this issue. Thanks for the report!
