### ISSUE TITLE
Loupe does fall outside the limits of the image

### ISSUE THREAD

**Issue by guilleholmann** [redoPop/loupe#17]
Hi All,

I want to create a "magnifying glass" / "lens zoom" 

I'm attaching an example here.
![captura de pantalla 2017-05-20 a la s 20 04 02](https://cloud.githubusercontent.com/assets/8420964/26279896/cf0f1544-3d97-11e7-8fb3-f74dd2a4ddfc.png)

Is there an option for the loupe not to go outside the image limits?

Thank you!

**Comment by redoPop** [comment]
By default, the magnifier lens is appended directly to the `document.body` to avoid being clipped by any overflow:hidden containers.

Clipping can be enabled by making the lens a sibling of the image itself, e.g.:

```html
<div style="overflow:hidden">
	<img style="width: 100%" id="my-image" src="big.jpg" />
</div>
```

```javascript
const loupe = new Loupe(document.getElementById('my-image'));
loupe.el.parentNode.insertBefore(loupe.lens, loupe.el.nextSibling);
```
